"""Preserve the measured existing arrangement and make host interfaces explicit."""
import json,hashlib
from pathlib import Path
R=Path(__file__).resolve().parents[1];i=json.loads((R/'architecture/existing-R09-interface.json').read_text())
i['revision']='M01';i['validation_status']='Existing R09 placement preserved; new authored geometry pending verification.'
i['source_layout']={'path':'C:/Users/Camer/Games/critical-shift/worktrees/medical-reanimation/sections/medical-reanimation/blender/ocru.blend','survey':'architecture/existing-saved-survey.json','sha256':json.loads((R/'architecture/existing-saved-survey.json').read_text())['sha256']}
i['portals'][0].update(owner='medical-reanimation',outward_normal=[0,-1,0],external_face=[0,-.18,0],mechanism='opposed sliding pressure leaves; open traversal default; closed state separately tested')
i['utilities']=[{'id':'MED_POWER','center':[-2.15,9.18,2.65],'outward':[0,1,0],'size':[.2,.2],'owner':'medical-reanimation','state':'capped unbound power socket'}, {'id':'MED_WATER','center':[3.36,10.70,.6],'outward':[1,0,0],'size':[.12,.12],'owner':'medical-reanimation','state':'capped unbound wash supply'}, {'id':'MED_DRAIN','center':[2.33,11.30,.15],'outward':[0,1,0],'size':[.15,.15],'owner':'medical-reanimation','state':'capped controlled drain'}, {'id':'MED_EXTRACT','center':[2.33,11.30,2.25],'outward':[0,1,0],'size':[.4,.3],'owner':'medical-reanimation','state':'capped decon extract'}, {'id':'MED_DATA','center':[-.4,9.18,2.65],'outward':[0,1,0],'size':[.12,.12],'owner':'medical-reanimation','state':'capped employee telemetry'}]
i['host_hooks']=[{'id':'OCRU_LOAD','purpose':'adult transfer berth and recoverable ragdoll insertion'}, {'id':'OCRU_SUIT_PORT','purpose':'suit service coupling'}, {'id':'OCRU_CARTRIDGE','purpose':'medical cartridge insertion/stock consumption'}, {'id':'OCRU_RESTART','purpose':'physical short restart sequence'}, {'id':'OCRU_POWER','purpose':'normal/reserve choice; low-power pause and resumption'}, {'id':'OCRU_MAINTENANCE','purpose':'fault repair access'}, {'id':'DECON_WAND','purpose':'gross contamination removal before chamber loading'}, {'id':'RECOVERY_EXIT','purpose':'revived worker recovery and egress'}, {'id':'OCRU_COMPLIANCE_LOCK','purpose':'remote lock/identity/firmware host state'}, {'id':'AUDIO_MEDICAL','purpose':'room audio zone'}]
i['host_responsibility']='Geometry provides editable mechanisms and anchors. Runtime owns authority/network replication, occupancy, power cost, cartridge inventory, state sequencing, contamination, locks, ragdoll physics and temporary debuffs. No gameplay implementation claimed.'
i['implementation_decisions'] += ['Latest user explicitly asks to retain existing layout as the baseline; no relocation of equipment or decon alcove without measured cause.','Rear alcove remains decontamination. A hose/wand serves the adjacent cart apron so a long cart need not rotate inside the narrow alcove. Handheld use and contamination rules belong to host.','Reserve battery cabinet and rear console remain at inherited placements; no direct Waste discharge is routed through the treatment room.','Fuel Corridor S02_CLEAN is a separate unbound clean header (6.6,21,0),2.0x2.5; Medical entry2.2x2.5. Shared service-junction placement remains connector-owner work; no invented global transform.']
(R/'interface.json').write_text(json.dumps(i,indent=2))
