from pathlib import Path
import json,hashlib,datetime,collections
ROOT=Path('/workspace/critical-shift');R=ROOT/'sections/facility-assembly/sources/compliance-dock';P=R/'revamp/production';O=P/'critics/full-c07-technical';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();source='22176ab474d914156cdf5a083571c19b04c6e6e11cfa50ab8ba681013bc124a6'
I=json.loads((O/'native-inventory.json').read_text());V=json.loads((O/'existing-validator.json').read_text());D=json.loads((O/'drum-actual-interpenetration.json').read_text());N=json.loads((O/'resources-normals.json').read_text());images=json.loads((O/'formal-image-verification.json').read_text()); refs=json.loads((O/'reference-manifest-verification.json').read_text());protected=json.loads((P/'protected-inputs.json').read_text());frozen=[{'path':str(ROOT/p),'expected':h,'actual':sha(ROOT/p),'match':sha(ROOT/p)==h} for p,h in protected.items()];assert sha(R/'module_overhaul_R1.blend')==source and sha(P/'checkpoints/full-f13.blend')==source and all(x['match'] for x in frozen)
notes={
'C01_ENTRY':'No missing surfaces or obvious unsupported major equipment; closed G1 state is authored, open clearance checked separately.',
'C02_HERO_DOCK':'Major machinery and hatch are seated; clipping concern belongs to detailed native tests, not view names.',
'C03_CHECKIN_COUNTER':'Door reader, junction, hatch stanchions and desk equipment show plausible contacts; native registered seats tested.',
'C04_SCANNER_APPROACH':'No visible crown gap; hidden overlap nevertheless measured independently.',
'C05_CONVEYOR_LEAD_TUNNEL':'Curtain/clamp and conveyor visibly joined; native rib seat rays agree; some exposed co-oriented shield/cosmetic skins remain.',
'C06_CART_GATE_G1':'Retained gates and track visibly join; saved state is closed.',
'C07_OFFICE_INTERIOR':'Desk/chair feet and upholstery read as supported; checker examined separately.',
'C08_CONCEALED_SUPPORT_H1':'Tarp has continuous weave and supported trolley; no obvious floating clip in pixels.',
'C09_ARRIVAL_GATE_P2':'Sealed leaves and cassettes show intact depth; open P2 operation remains unverified.',
'C10_ROOF_SERVICES':'Roof fixtures appear connected; P1 lintel/corridor same-facing surface overlap is visible near lower right, supported by camera rays.',
'CORNER_SW':'Cutaway coverage inspected; no unregistered major detached asset seen.',
'CORNER_SE':'Cutaway coverage inspected; no unregistered major detached asset seen.',
'CORNER_NW':'Cutaway coverage inspected; overlapping drum silhouettes remain in service corner.',
'CORNER_NE':'Cutaway coverage inspected; overlapping drum silhouettes remain in service corner.',
'WALL_SOUTH':'Entry opening and inherited corridor presentation intact; cutaway is not a runtime doorway test.',
'WALL_NORTH':'Sealed arrival framing and supported cabinets remain intact.',
'WALL_EAST':'Service corner drums overlap; utility cabinet and conduit contacts appear intact.',
'WALL_WEST':'Office wall cutaway reviewed; hidden cutaway panels explain isolated trim display.',
'HERO_SCANNER':'Actual inner sensing pockets and bridge present; seat overlap is hidden in this beauty view.',
'HERO_CARGO':'Shield rib/collar construction visible; coincident cosmetic shield skins corroborated by rays.',
'HERO_EVIDENCE':'Cabinet/handles appear seated; no missing material or dependency symptom.',
'HERO_TROLLEY':'Cover checker is continuous on broad drape; caster/frame contacts present.',
'HERO_UTILITIES':'Transit drum top/rim overlap directly visible at about827,498; standalone solids intersect in native.',
'DETAIL_CHECKIN':'Cloth/paper and speaking assembly contacts appear intact; textile cut-chart examined numerically.',
'PLAYER_REVERSE':'P1 side reveals and head retain directly exposed duplicate same-facing skins; ray witnesses near x457/610 and y214–379.',
'PLAYER_PINCH':'Intersecting drums visible near754,296; walkway reservation remains static-clear.',
'WALL_OFFICE_FRONT':'No visible floating door-reader/notice construction; native root/seat checks also pass.'}
for r in images:
 r['opened_individually_original_resolution']=True
 r['technical_observation']=notes[r['id']] if r['batch']=='full-cycle-07' else ('Neutral light confirms same geometry and drum clipping; no missing shader response or dependencies.' if r['batch'].endswith('neutral') else 'Checker coverage on exposed sides/caps reviewed; cloth uses actual continuous cut chart, hard surfaces physical face charts. Drum overlap persists.')
(O/'pixel-inspection.json').write_text(json.dumps({'current_images':images,'approved_references':refs['images'],'total_current_images':35,'total_reference_images':4,'visual_score':None},indent=2))
findings=[
 {'id':'T8-01','severity':'high','critical':False,'title':'Separate transit drums visibly interpenetrate','objects':['Transit drum A','Transit drum B'],'evidence':{'horizontal_center_distance_m':D['horizontal_center_distance_m'],'measured_solid_overlap_length_m':D['evaluated_cross_sections'][2]['solid_overlap_length_m'],'cross_section_heights_m':[x['z_m'] for x in D['evaluated_cross_sections']],'top_coplanar_overlap_m2':D['top_overlap_m2'],'views':[{'id':'HERO_UTILITIES','pixel':[827,498]},{'id':'PLAYER_PINCH','pixel':[754,296]}]},'raw':['drum-actual-interpenetration.json','drum-probe.log','named-view-coplanar-visibility.json'],'assessment':'147.869mm actual solid overlap, rather than contact or a bounding-box near miss. Blue/yellow separate drum bodies cannot share this volume. Classified high localized prop clipping, not catastrophic room/interface/dependency loss.'},
 {'id':'T8-02','severity':'medium','critical':False,'title':'Exposed P1 reveal/head skins retain co-oriented coplanar duplicates','objects':['P1 corridor wall E','South wall east','P1 corridor wall W','South wall west','P1 corridor ceiling','South lintel P1'],'evidence':{'representative_east_triangle_overlap_m2':0.48043544228952095,'representative_bottom_head_triangle_overlap_m2':0.31999201078534184,'head_surface_z_m':2.5999999,'materials':['CD | plaster','CD | charcoal'],'views':['PLAYER_REVERSE','C10_ROOF_SERVICES']},'raw':['coplanar-overlap.json','named-view-coplanar-visibility.json'],'assessment':'Same outward normals, positive triangle-area overlap, and camera-first-hit witnesses establish exposed skins. These are different from opposed hidden contact faces. Exact whole-object duplicate checks cannot detect them. Not every broad probe candidate is scored as a defect: buried carcass/plinth contacts and corner caps are legitimate.'},
 {'id':'T8-03','severity':'medium','critical':False,'title':'Scanner manufactured crown and bridge do not conform within 2mm','objects':['Scanner portal column -1','Scanner portal column 1','Scanner portal lintel'],'evidence':{'y_m':7,'absolute_x_m':[.66,.76,.81],'measured_penetration_m':[.005886554718017578,.009180307388305664,.0039043426513671875],'at_x_076_column_top_z_m':2.6684112548828125,'at_x_076_bridge_bottom_z_m':2.659230947494507,'views':['C04_SCANNER_APPROACH','HERO_SCANNER']},'raw':['actual-bearing-surfaces.json','bearing-probe.log'],'assessment':'Bidirectional rays independently measure both evaluated surfaces. Both crowns have the same3.9–9.2mm mismatch. This is hidden engaged geometry, not floating or a visible hero failure; it exceeds the recommended2mm penetration allowance for a clean bearing. A guard ray to the bridge from an expected mathematical crown point does not measure the actual column crown.'}
]
limits=['No full builder or native save was run. Rebuild determinism from factory-empty source is therefore unverified; static current/checkpoint recipe hashes match native-recorded hashes and all recipes are retained.','This review cold-opened the native source repeatedly with pinned Blender, but did not cold-render all35 views itself or test a separately relocated checkout. The supplied35 images were hash-verified and individually inspected.','Static validator uses labelled bulky obstacles plus inferred architecture and declared open poses; this is not engine physics, collision ownership, navigation, import, runtime FPS/draw calls, animation, or moving-door sweep proof. P2 open aperture/operation remains explicitly unverified.','All2732 evaluated connected islands have actual sampled surfaces/intersection evidence; finite nearest-point sampling cannot certify every buried penetration or continuous structural load path.22 sparse-contact candidates were refined with all vertices and BVH triangle intersections and all proved engaged.','All92 registered anchors were measured against target surfaces and independently recomputed component seats. The40 cargo rib seat samples and6 scanner crown/bridge pairs use both actual surfaces. Internal fixing-sized disconnected parts are included in island probes; individual fastener strength, torque and every full fixing-seat penetration were not exhaustively certified.','Same-facing coplanar candidate counts are not a defect count. Of2520 positive pair overlaps, many are buried or legitimate corner/seat contacts. Decisive findings use visible perspective-view rays and actual object construction. The recorded orthographic camera rays use an explicitly documented perspective approximation; those results are excluded from decisive findings.','The local36 material families consume no images. All119 packed file images belong to linked read-only map context. Packed payloads and dependency hashes were verified, but a new full third-party licensing audit of the immutable assembled map was not performed. The local delivered font is packed, resolves relatively, and has a matching retained DejaVu license.','Physical charts are finite and preserve every tested evaluated edge over0.1mm within1%; actual textile shaders use CD_Fabric_Cut_1m. Their continuous area-normalized/projected charts intentionally have local distortion: tarp edge ratios0.848–1.085, cushion maxima1.668–1.779, tiny seam/return charts down to0.445. Global area normalization is not local isometry or a unique/lightmap atlas claim.','Native envelope follows the measured preserved source, including floor X bounds±7.1m, versus contract exterior wall allowance±7.08m. Blueprint labels are not presented as newly verified whole envelope dimensions.']
report={'schema_version':1,'review':'fresh independent read-only formal category8 technical review','generated_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'category':8,'category_name':'Technical cleanliness, support contact, reproducibility and dependencies','score':90.0,'score_max':100,'verdict':'FAIL — category8 does not satisfy strictly greater than93','overall_visual_score':None,'critical_count':0,'severity_counts':{'critical':0,'high':1,'medium':2,'low':0},'source':str(R/'module_overhaul_R1.blend'),'scene':'COMPLIANCE_EDIT_LOCAL','source_sha256':source,'source_unchanged_end':True,'checkpoint_identical':True,'blender':'5.2.2 LTS d13f752e3b9c','threads':1,'formal_evidence':{'beauty':27,'neutral':4,'uv':4,'all_manifests_complete':True,'all_image_hashes_match':True,'approved_reference_images':4,'all39_images_opened_individually_original_resolution':True},'counts':I['counts'],'baseline_counts':{'objects':1077,'evaluated_triangles':297672,'material_submeshes':992,'materials':24},'planning_caps':{'triangles':450000,'material_submeshes':1150,'local_material_families':36,'pass':True},'native_geometry':{'inherited_objects_verified':len(I['inherited_matrices']),'max_world_matrix_delta':max(x['matrix_delta'] or 0 for x in I['inherited_matrices']),'connected_islands':2732,'closed_islands':1903,'open_islands':829,'negative_closed_volumes':0,'inconsistent_oriented_edges':0,'nonmanifold_edges':0,'zero_area_triangles':0,'physical_uv_bad_edges':0},'registered_support':{'assemblies':45,'anchors':92,'max_anchor_gap_m':max(x['gap_m'] for x in V['support_table']),'max_anchor_penetration_m':max(x['penetration_m'] for x in V['support_table']),'max_normal_error_deg':0},'validator_summary':V['summary'],'dependencies':{'relative_native_libraries':25,'all_resolved_and_hashed':True,'packed_file_images':119,'local_material_image_nodes':0,'font_packed_and_licensed':True,'all_native_recorded_recipes_match_current':True},'findings':findings,'limits_and_unverified':limits,'protected_inputs_end':frozen,'processes_and_read_handles_released':True,'failed_attempts_preserved':[{'script':'native_probe.py','log':'native-probe.log','failure':'Literal requested executable suffix blender5.2.2LTS did not exist; no Blender process ran; retry used verified blender executable.'},{'script':'refine_probe.py','log':'refine-probe.log','failure':'Missing closing parenthesis caused Python parse error; original retained, corrected separate retry script/log succeeded.'}],'raw_evidence_directory':str(O)}
(P/'critics/full-c07-technical.json').write_text(json.dumps(report,indent=2)+'\n')
md=f'''# Compliance dock C7 — independent technical category8 review

**90.0/100 — FAIL.** Category8 must be strictly greater than93. **Critical0; high1; medium2.** No overall visual score is assigned.

The frozen scene is `COMPLIANCE_EDIT_LOCAL` in `module_overhaul_R1.blend`, SHA256 `{source}`. The source and identical `full-f13.blend` checkpoint remain byte-exact. Every protected input and native-recorded source/font/license recipe hash matches. All27 beauty,4 neutral and4 UV images were complete and independently hash-verified before final review; I opened all35 individually at original resolution, plus the4 approved spawn references. [Image inspection ledger](full-c07-technical/pixel-inspection.json).

## Defects that prevent category acceptance

1. **High — two transit drums visibly intersect.** Actual evaluated side rays at Z0.15,0.30,0.50,0.70 and0.85m show **147.869mm** shared solid length. Centers are0.328024m apart; top skins share0.0319285m². This is separate blue/yellow drum volume, not a joint or box-based suspicion. It is visible in [HERO_UTILITIES](../renders/full-cycle-07/HERO_UTILITIES.png), near pixel827,498, and [PLAYER_PINCH](../renders/full-cycle-07/PLAYER_PINCH.png), near754,296. [Actual triangles/cross sections](full-c07-technical/drum-actual-interpenetration.json).
2. **Medium — P1 exposed reveal/head skins are coplanar duplicates.** Corridor side skins and south-wall reveals share the same outward planes; a representative east-side triangle overlap is0.480435m². Corridor ceiling and south lintel share the downward surface at Z2.60m; a representative triangle overlap is0.319992m², with charcoal/plaster assignments. First-hit camera rays place these skins directly in [PLAYER_REVERSE](../renders/full-cycle-07/PLAYER_REVERSE.png) and [C10_ROOF_SERVICES](../renders/full-cycle-07/C10_ROOF_SERVICES.png). This differs from opposed hidden contact faces. [Coplanar measurements](full-c07-technical/coplanar-overlap.json) and [named-view witnesses](full-c07-technical/named-view-coplanar-visibility.json).
3. **Medium — scanner crowns do not conform to bridge underside.** Downward rays to the actual crowns and upward rays to the bridge measure3.904–9.180mm hidden penetration at six samples. At X±0.76,Y7m, column top is Z2.668411m and bridge underside Z2.659231m. The seam has engagement, but misses the recommended2mm clean-bearing allowance. Testing only the bridge against a mathematical expected crown point cannot establish the real joint. The mismatch is hidden in [HERO_SCANNER](../renders/full-cycle-07/HERO_SCANNER.png); it is not called a visible floating hero or a critical room failure. [Both actual surfaces](full-c07-technical/actual-bearing-surfaces.json).

## What independently passed

| Measurement | Actual result |
|---|---:|
| Evaluated triangles / cap |385,180 /450,000|
| Authoring material submeshes / cap |1,149 /1,150|
| Local used material families / cap |36 /36|
| Inherited objects retained |1,077|
| Maximum inherited world-matrix delta |1.1921×10⁻⁷m|
| Supported assemblies / actual anchor seats |45 /92|
| Maximum registered anchor gap or penetration |2.3842×10⁻⁷m|
| Evaluated connected islands |2,732|
| Closed / intentionally open islands |1,903 /829|
| Zero-area triangles, inconsistent directed edges, nonmanifold edges, negative closed volumes |0 each|
| Native relative linked dependencies |25, all resolved and hashed|
| Packed inherited file images |119, payloads hashed|

[Fresh existing validator](full-c07-technical/existing-validator.json) passed7 checks with0 errors/0 warnings, using explicit `contracts/interface.json`. Its pass does not erase the finer defects above. Interior clear faces measure X±6.80000019m and Y≈0/15.80000019m. Sampled usable widths are P1 2.39999986m, D1/D2 1.04999930m, human scanner1.21999979m, G1 1.85999960m, and north return1.54999876m. Saved closed doors and declared open poses are distinguished. Floor envelope remains inherited X±7.1m, not claimed to equal the contract's±7.08m wall allowance.

Every evaluated disconnected island received real BVH surface samples rather than bounds-only acceptance.22 initial sparse-contact warnings were refined using all evaluated vertices plus actual triangle intersection; all proved engaged, including glazing/mullions, curtains/clamps, cart hoop and scanner conduits. The40 cargo rib-to-shield seat samples match within0.24µm. Hidden carcass/plinth joints and intersecting seats are separated from same-outward exposed skins. [Island probes](full-c07-technical/island-surface-contacts.json), [refinements](full-c07-technical/refined-contact-candidates.json), [bearing probes](full-c07-technical/actual-bearing-surfaces.json).

Actual shader-output traversal confirms physical UV use for hard surfaces and `CD_Fabric_Cut_1m` for textiles. Every tested physical edge over0.1mm preserves metric length within1%, with no collapsed geometry/UV triangles. Actual textile charts are finite and continuous on the visible broad cloth: tarp top area ratio1.000000054; upholstery total area ratios≈1.0. Local textile distortions remain (tarp0.848–1.085 edge ratios; cushion maxima1.668–1.779; small return/seam charts down to0.445), so the independent physical audit chart is not substituted for the consumed cloth coordinates. No atlas/lightmap claim is made. [Actual consumed UVs](full-c07-technical/consumed-textile-uv.json), [shader and packed-resource hashes](full-c07-technical/resources-normals.json).

Fresh pinned Blender5.2.2 LTS (`d13f752e3b9c`), threads1, repeatedly cold-opened the source with25 relative native dependencies. Local room shaders consume no images; all119 packed images belong to immutable linked map context. The packed local DejaVu font resolves relatively and its retained license hash matches. [Cold dependency results](full-c07-technical/portability.json), [recipe comparison](full-c07-technical/recipe-verification.json).

## Limits and reproducibility

'''+''.join(f'- {x}\n' for x in limits)+'''
The failed literal executable-path attempt and failed first coplanar probe parse are preserved with their original scripts/logs; successful retries are separate. No builder, modeling pipeline, native save, source repair, or protected input edit was run. All my Blender processes have exited and all subprocess sessions and file/image read handles are released. [End source/protection/resource audit](full-c07-technical/input-hashes-end.json).
'''
(P/'critics/full-c07-technical.md').write_text(md)
end={'source_sha256':sha(R/'module_overhaul_R1.blend'),'checkpoint_sha256':sha(P/'checkpoints/full-f13.blend'),'protected':frozen,'all_read_handles_released':True,'all_blender_processes_exited':True,'raw_files_sha256':[{ 'path':str(p.relative_to(O)),'sha256':sha(p)} for p in sorted(O.iterdir()) if p.is_file() and p.name!='input-hashes-end.json']};(O/'input-hashes-end.json').write_text(json.dumps(end,indent=2)+'\n');print('REPORT_WRITTEN',report['score'],report['verdict'])
