"""Generate the seconds-based RUNTIME BEHAVIOUR SPEC of the control room from the built blend (the engine cannot import Blender drivers).
usage: python cr_runtime_spec.py -- <blend> <out_dir> [--prefix CR]
Writes control_room_runtime_behaviour.json and .md: every in-scope driver as (target, expression in seconds, inputs), the TV schedule
sampled in seconds, and the stability input contract. T = scene time in seconds; s = reactor stability (REACTOR_STATE.stability, 0..1).
Evidence: this is a specification generated from the authoring file. It is NOT an engine implementation and NOT a measurement."""
import bpy,sys,os,json
A=sys.argv[sys.argv.index("--")+1:]; SRC,OUT=A[0],A[1]; PFX=A[A.index("--prefix")+1] if "--prefix" in A else "CR"
bpy.ops.wm.open_mainfile(filepath=SRC); sc=bpy.context.scene
rows=[]
for coll in (bpy.data.objects,bpy.data.materials,bpy.data.lights,bpy.data.node_groups):
    for i in coll:
        for host in (i,getattr(i,"node_tree",None),getattr(i,"data",None)):
            ad=getattr(host,"animation_data",None) if host is not None else None
            if not ad or not (i.name.startswith(PFX)): continue
            for fc in ad.drivers:
                d=fc.driver
                ins={v.name:(v.targets[0].id.name+v.targets[0].data_path if v.targets[0].id else v.targets[0].data_path) for v in d.variables if v.name not in("fps","fb")}
                rows.append({"owner":i.name,"kind":type(i).__name__,"target":fc.data_path+("[%d]"%fc.array_index if fc.array_index>=0 else ""),"expression":d.expression.replace("(frame*fb/fps)","T").replace("frame*fb/fps","T"),"inputs":ins})
def at(T):  # TV state at scene time T, evaluated in Blender at 30 fps
    f=T*30; sc.frame_set(int(f),subframe=f-int(f)); bpy.context.view_layer.update()
    E=bpy.data.objects["CR_TV"]; L=[o for o in bpy.data.objects if o.name.startswith("CR TV") and o.type=='LIGHT']
    return {"t":T,"w_tel":round(E["w_tel"],4),"w_bro":round(E["w_bro"],4),"w_sta":round(E["w_sta"],4),"w_bar":round(E["w_bar"],4)}
tv=[at(round(k*0.25,2)) for k in range(0,81)]
spec={"time_base":"seconds of scene time T; frame-rate independent (verified by fps_independence_check.py, 24-480 fps)","inputs":{"s":"reactor stability 0..1 (REACTOR_STATE.stability); engine feeds the host-authoritative value","T":"seconds on the controlled simulation/presentation clock"},
 "tv":{"cycle_seconds":20.0,"states":["w_tel","w_bro","w_sta","w_bar"],"weights_sum":1.0,"samples_every_0.25s":tv,"custom_clip":"w_clip=1 disables the cycle; play the clip by time, light colour/energy from tv_light_track.json track_time_s"},
 "drivers":rows,"status":{"engine_implementation":"Blocked (no Unity target)","measured_performance":"NotRun"}}
os.makedirs(OUT,exist_ok=True); json.dump(spec,open(os.path.join(OUT,"control_room_runtime_behaviour.json"),"w"),indent=1)
md=["# Control room runtime behaviour (seconds based)\n","Generated by `cr_runtime_spec.py` from the authoring blend. Spec only: not an engine implementation, not measured.\n",
 "- `T` = seconds on the simulation clock; `s` = reactor stability 0..1. Nothing depends on the display frame rate.","- TV cycle: 20 s loop, weights `w_tel/w_bro/w_sta/w_bar` (sum 1) from the piecewise-linear schedule in `control_room_runtime_behaviour.json` (`tv.samples_every_0.25s`).\n",
 "| owner | target | expression (T in seconds) |","|---|---|---|"]
for r in rows: md.append("| %s | `%s` | `%s` |"%(r["owner"],r["target"].replace("|","/"),r["expression"].replace("|","/")))
open(os.path.join(OUT,"control_room_runtime_behaviour.md"),"w").write("\n".join(md)+"\n"); print("drivers",len(rows),"tv samples",len(tv))
