"""Real-time light budget for the control room (run on a built/optimised blend).
usage: python cr_rt_lights.py -- <in.blend> <out.blend> <spec_dir>
A real-time engine cannot run ~18 shadowed dynamic lights.  Budget: DYNAMIC (6, at most 2 shadow casters) = three troffers (flicker/brownout/stability),
the TV light (follows the picture), two red beacons.  Everything else is BAKED (lightmap) at its rest value: its Blender driver is removed and its energy
frozen, flagged with custom props rt_mode / rt_note.  The flicker cue of the baked CRT/rack lights is carried by the emissive screens and LEDs (their
drivers stay).  Writes control_room_light_budget.json/.md.  Spec only: nothing here is engine-measured."""
import bpy,sys,os,json
A=sys.argv[sys.argv.index("--")+1:]; SRC,DST,OUT=A[0],A[1],A[2]
bpy.ops.wm.open_mainfile(filepath=SRC)
DYN={"CR troffer -3.0":False,"CR troffer -0.6":True,"CR troffer 1.2":False,"CR tv light":True,"CR beacon +x":False,"CR beacon +y":False}   # name -> casts a real-time shadow
REST={"CR rack batten":30.0,"CR crt glow -1.05":7.0,"CR crt glow -2.75":7.0,"CR crt glow 0.65":7.0}                                         # driver-free rest values (stability 1, no flicker)
rows=[]
for o in bpy.data.objects:
    if o.type!='LIGHT' or not o.name.startswith("CR "): continue
    l=o.data; dyn=o.name in DYN
    if not dyn:
        if l.animation_data:
            for fc in list(l.animation_data.drivers): l.driver_remove(fc.data_path)
        if o.name in REST: l.energy=REST[o.name]
        l.use_shadow=True                                             # the bake wants shadows; the engine light is a lightmap, so no real-time shadow
    o["rt_mode"]="dynamic" if dyn else "baked"; o["rt_shadow"]=bool(DYN.get(o.name,False))
    o["rt_note"]=("driven in the engine from the seconds-based spec" if dyn else "lightmap bake at rest value; flicker carried by emissive screens/LEDs")
    rows.append({"name":o.name,"type":l.type,"mode":o["rt_mode"],"realtime_shadow":o["rt_shadow"],"rest_energy_W_cycles":round(l.energy,2),"color":[round(c,3) for c in l.color],"location":[round(v,3) for v in o.location]})
os.makedirs(OUT,exist_ok=True)
nd=sum(r["mode"]=="dynamic" for r in rows)
spec={"dynamic_lights":nd,"realtime_shadow_casters":sum(r["realtime_shadow"] for r in rows),"baked_lights":len(rows)-nd,"lights":rows,"status":{"engine_implementation":"Blocked (no Unity target)","measured_performance":"NotRun"}}
json.dump(spec,open(os.path.join(OUT,"control_room_light_budget.json"),"w"),indent=1)
md=["# Control room real-time light budget\n","Spec generated by `cr_rt_lights.py`. Not engine-measured. Dynamic lights follow `control_room_runtime_behaviour.json` (seconds-based drivers).\n","| light | mode | shadow | rest W (Cycles) | colour |","|---|---|---|---:|---|"]
md+=["| %s | %s | %s | %s | %s |"%(r["name"],r["mode"],"yes" if r["realtime_shadow"] else "no",r["rest_energy_W_cycles"],r["color"]) for r in rows]
open(os.path.join(OUT,"control_room_light_budget.md"),"w").write("\n".join(md)+"\n")
print("dynamic",nd,"shadow casters",spec["realtime_shadow_casters"],"baked",len(rows)-nd)
bpy.ops.wm.save_as_mainfile(filepath=DST)
