"""Refinery metric layout; Z up, south/front = -Y. No external downloads."""
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
PRODUCTION = ROOT/'production'
BLEND = ROOT/'blender'/'Refinery.blend'
ROOM = (14.0, 12.0, 4.8)
EYE = 1.68
ROUTE_WIDTH = 2.2
SEED = 7092026
MACHINES = ['RECEIVING','FEEDER','CRUSHER','SORTER','PROCESSOR','DRYER','ASSEMBLY','INSPECTION','DISPATCH']
CAMERAS = {
 'CAM_ENTRY': ((-1.8,-5.45,EYE),(0,3.5,1.7),23),
 'CAM_MINE_TO_CRUSHER': ((-2.6,-5.0,EYE),(-5.0,1.6,1.65),21),
 'CAM_MAIN_ROUTE': ((-3.15,-.9,EYE),(2.0,3.5,1.65),22),
 'CAM_PROCESS': ((-.8,1.4,EYE),(1.0,4.5,1.8),20),
 'CAM_ASSEMBLY': ((1.6,-3.5,EYE),(5.35,.4,1.45),22),
 'CAM_REVERSE': ((3.4,2.35,EYE),(-3.6,-2.0,1.35),22),
 'CAM_PINCH': ((-2.7,2.05,EYE),(-4.0,4.6,1.6),22),
 'CAM_MATERIAL': ((3.15,-.5,EYE),(5.3,1.2,1.2),30),
}
COLLECTIONS = ['ARCHITECTURE','MACHINES','CONVEYORS','UTILITIES','PROPS','LIGHTING','INTERACTION','VALIDATION','CAMERAS']
CHAIN = ['ORE CHUNKS','ORE BATCH','CRUSHED BATCH','SORTED BATCH','PROCESSED MATERIAL','DRIED MATERIAL','FUEL COMPONENTS','FUEL ASSEMBLY','INSPECTION RESULT','REACTOR DELIVERY']
REQUIRED_MARKERS = ['INT_RECEIVING_'+r for r in ['CART_DOCK','HOPPER','BRAKE','LATCH','TIP','SIZE_GATE','SPILL_CLEANUP','MINE_ROUTE']]
