<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../CriticalShift.Features.Interaction.Domain/CriticalShift.Features.Interaction.Domain.csproj" />
    <ProjectReference Include="../CriticalShift.Features.Session.Domain/CriticalShift.Features.Session.Domain.csproj" />
  </ItemGroup>
</Project>
